### ISSUE TITLE
Where the generated track are merged

### ISSUE THREAD

**Issue by yangshiyan** [gemc/source#238]
Dear developers:
        I noticed that the option MERGE_LUND_BG can be used to merge tracks from background file “filename”: 
        -MERGE_LUND_BG="filename"
       However,  I didn't find the corresponding implementation function and process. Can you tell me which function is used to implement this process? I'm more curious about the implementation of this process。
       Thank you very much.
       Best regards.

**Comment by maureeungaro** [comment]
Hello:

The implementation is done in src/MPrimaryGeneratorAction.cc starting at line 790.

In general, to use this, you would first run gemc to produce background, with option SAVE_ALL_MOTHERS=3, so that any particle that produces a hit is saved in the LUND file. 

This first step is the one that could take a significant amount of time, and the MERGE_LUND_BG options allow one to use these saved particles to produce a background instantly. 

Let me know if this helps!

Mauri

**Comment by yangshiyan** [comment]
I understand, thank you very much.
